package com.localbitcoins.pojo.advertisment

import com.localbitcoins.pojo.Profile

data class AdvertismentData (
    val profile: Profile,
    val requireFeedbackScore: Int,
    val hiddenByOpeningHours: Boolean,
    val tradeType: String,
    val adId: Int,
    val tempPrice: String,
    val bankName: String,
    val paymentWindowMinutes: Int,
    val trustedRequired: Boolean,
    val minAmount: String?,
    val accountInfo: String,
    val visible: Boolean,
    val referenceType: String,
    val requireTrustedByAdvertiser: Boolean,
    val trackMaxAmount: Boolean,
    val tempPriceUsd: String,
    val lat: Double,
    val isLocalOffice: Boolean,
    val priceEquation: String,
    val firstTimeLimitBtc: String?,
    val city: String,
    val locationString: String,
    val countrycode: String,
    val currency: String,
    val limitToFiatAmounts: String,
    val createdAt: String,
    val maxAmount: String?,
    val lon: Double,
    val displayReference: Boolean,
    val smsVerificationRequired: Boolean,
    val requireTradeVolume: Double,
    val onlineProvider: String,
    val maxAmountAvailable: String,
    val openingHours: String,
    val msg: String,
    val requireIdentification: Boolean,
    val volumeCoefficientBtc: String,
    val atmModel: String?
)
